"""add product size

Revision ID: aecbbf5641a2
Revises: e21c9a0c75bf
Create Date: 2026-09-09 16:40:22.420289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecbbf5641a2'
down_revision: Union[str, Sequence[str], None] = 'e21c9a0c75bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size')
    # ### end Alembic commands ###
