"""add apple sign in

Revision ID: cdd30b0324f3
Revises: 67fbb969646d
Create Date: 2026-09-09 17:39:13.762884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd30b0324f3'
down_revision: Union[str, Sequence[str], None] = '67fbb969646d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apple_sub', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['apple_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'apple_sub')
    # ### end Alembic commands ###
